### ISSUE TITLE
how to train the code in idr dataset

### ISSUE THREAD

**Issue by qiuyuenheng** [shaomq2187/TransPIR#10]
I tried applying the IDR dataset to your code, but it seems that I'm unable to reconstruct the mesh correctly. The reconstructed mesh and the interaction points of the first collision are shown in the following image. Do you have any suggestions? Is it possible that using the camera pose files provided by the IDR dataset directly is incorrect?
![1714900185697](https://github.com/shaomq2187/TransPIR/assets/45327791/aa05beb7-77a7-4afb-8e45-ae08427f8a1c)

**Comment by s1752729916** [comment]
Sorry, this project has been too long and I can't remember all the details.
I encountered this problem in the early stage of this project because I confused the camera coordinate system. I cannot guarantee if your problem is related to this since I did not change the IDR coordinate system, but you can confirm the camera coordinate system to exclude this possibility

**Comment by qiuyuenheng** [comment]
> Sorry, this project has been too long and I can't remember all the details. I encountered this problem in the early stage of this project because I confused the camera coordinate system. I cannot guarantee if your problem is related to this since I did not change the IDR coordinate system, but you can confirm the camera coordinate system to exclude this possibility

Thank you for your reply! Can you recall the details of the coordinate system used when creating the dataset? For example, the specific directions of the XYZ axes. I consulted the documentation of the UR5 robot mentioned in your paper, as shown in the following image. It seems that its pose is in the same coordinate system as COLMAP. That's why I didn't modify the coordinate system directions and directly used the pose files from IDR.

![1714904328945](https://github.com/shaomq2187/TransPIR/assets/45327791/bf75fd3b-832b-4767-aee3-ca3e2234df37)
![1714904347891](https://github.com/shaomq2187/TransPIR/assets/45327791/253ef204-2616-4c2d-9ffc-a19e47ae23d0)

**Comment by s1752729916** [comment]
I checked my previous data processing code and its coordinate system is consistent with colmap/idr. So it shouldn't be a coordinate system issue. Can you provide more information about training? How did you apply the IDR dataset to our code? Have you changed the Dataset class or anything else?

**Comment by qiuyuenheng** [comment]
> I checked my previous data processing code and its coordinate system is consistent with colmap/idr. So it shouldn't be a coordinate system issue. Can you provide more information about training? How did you apply the IDR dataset to our code? Have you changed the Dataset class or anything else?

Okay, here are the modifications I made:

first，I removed the 'aolp_render_loss' from the source code because the IDR dataset doesn't have polarization data. i kept only the 'mask_loss' and 'eikonal_loss'.I have tested the code and there is no problem.

second，I used the 'camera.npz' pose files generated by the Neus project. These pose files are generated using the pose files and initial point cloud files from COLMAP. I manually removed redundant point clouds and kept only the regions of interest from the point cloud generated by COLMAP. This way, I  generated 'world_mat' and 'scale_mat' data that conforms to the IDR input. I have attached the corresponding code for "scale_mat" below, and also included the code for loading the 'camera.npz' file and converting it into pose and intrinsic parameters in our code.

Except for what I described above, all other parts are consistent with the original code.

![1714910317003](https://github.com/shaomq2187/TransPIR/assets/45327791/9ceb645a-11b6-4824-8800-2fe9a4431b02)
![1714910353280](https://github.com/shaomq2187/TransPIR/assets/45327791/d60b514a-9eff-4a82-95fe-c08f74da2b32)

**Comment by s1752729916** [comment]
I am not sure if the process of obtaining camera parameters from Neus is consistent with the IDR framework. Have you tried testing the DTU dataset used in [here](https://github.com/lioryariv/idr)

**Comment by qiuyuenheng** [comment]
> I am not sure if the process of obtaining camera parameters from Neus is consistent with the IDR framework. Have you tried testing the DTU dataset used in [here](https://github.com/lioryariv/idr)

Yes, I have also tried the pose file that comes with the IDR dataset, but it still doesn't work. So later on, I was considering whether it was because there was no normalized unit ball, so I used neus.

**Comment by s1752729916** [comment]
I suggest visualizing the DTU cameras and the cameras in our dataset to see if there are any significant differences between them

**Comment by qiuyuenheng** [comment]
> I suggest visualizing the DTU cameras and the cameras in our dataset to see if there are any significant differences between them

thank you！I'll give it a try！
