### ISSUE TITLE
paper里似乎有个关于SDF定义的小问题

### ISSUE THREAD

**Issue by WeihongPan** [shaomq2187/TransPIR#4]
又来打扰～
第二页 Method - Implicit Surface Representation
"The distance d is positive when x is inside the boundary, negative outside, and zero when x is on the boundary."
应该是negtive inside, positive outside？我看代码里似乎也是这么实现的

**Comment by s1752729916** [comment]
谢谢你的提醒！论文里应该刚好写反了，sdf 应该外正里负
