### ISSUE TITLE
关于给折射光赋固定值

### ISSUE THREAD

**Issue by WeihongPan** [shaomq2187/TransPIR#5]
你好，又是我～
在第四页的反射比例估计里写道：
Due to the total internal reflection, the values of It1 of some rays are unable to calculate from the 2-bounce ray tracer, in this case, we set It1 to a constant to avoid 100% reflection percentage since it is impossible in the real world.
意思是由于物体内部的全反射导致没有光线进入相机的现象在真实世界是不会发生的，所以要给没有值的二次折射光赋定值，但是这是个Inverse Rendering的过程，所以这里赋定值的是不是应该是It0，也就是第二次折射进入相机的光线？而不是It1，第一次折射进入物体内部的光线？

还有一个关于Illumination Sampling的问题
在第十页里写道：
where vc is the view direction and vs is the direction of the sampling ray
我理解这个vc应该指的是观测方向，也就是ray tracing里的ray direction
但是 [sampleEnvLight](https://github.com/shaomq2187/TransPIR/blob/51a79214b8f9303b6330ac921a0a50969fa3c4a6/coode/model/ray_tracing.py#L211) 里是把camera location设成了vc，这里我不是很理解

多有打扰，不好意思！

**Comment by s1752729916** [comment]
1、代码里的实现是按照It0(相机观测到的)，给哪个赋值对最终结果影响都不大，这里有赋值这么个操作主要是为了避免100%占比带来的一些问题；
2、因为相机的位姿经过归一化，世界坐标系原点就在物体的中心附近，相机指向物体中心的向量就可以写为`0 - cam_loc`，差个符号是因为实现的时候是计算余弦角度对v_c正负不敏感

**Comment by WeihongPan** [comment]
非常感谢您的耐心解答！
