### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by tuananh1007** [shaomq2187/TransPIR#6]
Thank you for sharing your work.

Could you share the raw RGB images (same as the one in the teaser) and GT reconstructed models?

Thank you!

**Comment by s1752729916** [comment]
The image in the teaser is the rendered picture of the reconstructed models in the Blender.  The raw images are  privided in the `./I-sum` of the dataset (the grayscale image or light intensity image). 

The GT models is available [here](https://cloud.tsinghua.edu.cn/f/0f589f9454514ab7b72a/?dl=1)
