### ISSUE TITLE
请问数据集里的法线图如何转换回相机坐标系

### ISSUE THREAD

**Issue by GCChen97** [shaomq2187/TransPIR#7]
Hi Mingqi, 

感谢开源了代码和数据集！我尝试把法线图从uint8[0, 255]转换到float[-1,1]，但发现有一小部分法线的norm不为1，所以想确认一下两个问题：

1.法线图的坐标系用的是colmap的定义(z-forward,x-right,y-down)还是opengl的定义(z-backward, x-right, y-up);
2.[-1,1]区间的法线是如何转换到[0,255]的;

感谢！

**Comment by GCChen97** [comment]
坐标系是opengl的定义。norm不为1可能是噪声。

**Comment by s1752729916** [comment]
1、坐标系opengl
2、就是简单的线性映射
法线不为1是正常的，因为神经网络学习到的不是标准的sdf函数，eikonal loss就是让法线逼近单位向量的

**Comment by GCChen97** [comment]
@shaomq2187 我看文章里写道真值用扫描仪获取的，以为法线也是测量出来的。所以说真值法线图其实是用某个隐式表面算法求出来的？

**Comment by s1752729916** [comment]
> @shaomq2187 我看文章里写道真值用扫描仪获取的，以为法线也是测量出来的。所以说真值法线图其实是用某个隐式表面算法求出来的？

sorry以为你问的是算法重建出来的模型的法线图。先用扫描仪扫出来真实模型，然后导入到unity里面手动配准之后渲染出来得到真值法线图，按理说norm应该是为1的，不为1的话可能就是你说的噪声了
