### ISSUE TITLE
IDR SILHOUETTE LOSS PARAMETERS #1

### ISSUE THREAD

**Issue by BanKeTang** [shaomq2187/TransPIR#9]
Hello, I saw in your paper you provided an initialization model for IDR reconstruction using only mask loss. Could you please provide the model parameters (.conf file) to achieve this result? Thank you.

**Comment by s1752729916** [comment]
We only use silhouette loss in the first 100 epochs, and add aolp loss later. You can modify the parameter `aolp_render_weight_milestones` in `coode/confs/fixed_cameras.conf` to 1000 to disable the aolp loss.

Alternatively, you can view the checkpoint of the 100th epoch
